server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeff_db
    username: jeff
    password: 123123..


logging:
  level:
    root: INFO
    org.springframework.beans.factory: debug
